import { ActiveLink } from "@/ui/atoms/ActiveLink";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "@/ui/organisms/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="pl">
			<body className={inter.className}>
				<Navbar />
				<main>{children}</main>
				<footer>
					<p className="text-center"> All rights reserved</p>{" "}
				</footer>
			</body>
		</html>
	);
}
